using UnityEngine;

namespace ChallengeShow
{
    /// <summary>
    /// Per-monster tuning data. One asset per unit; nothing about a unit is hard-coded in scripts.
    /// Values are authored by <c>ChallengeUnitAuthoringTools</c> from the source prefab's measured
    /// bounds, then hand-tuned. The challenge outcome is a consequence of these numbers plus the
    /// obstacle settings — never scripted per unit.
    /// </summary>
    [CreateAssetMenu(menuName = "Challenge Show/Unit Definition", fileName = "Unit_")]
    public class ChallengeUnitDefinition : ScriptableObject
    {
        public enum Locomotion
        {
            Biped,
            Quadruped,
            Hopper
        }

        [Header("Identity")]
        public string displayName = "Unit";
        [Tooltip("Untouched vendor prefab. Used for island display copies and as the variant base.")]
        public GameObject sourcePrefab;
        [Tooltip("Our prefab variant with body collider, rigidbody, motor and ragdoll. Generated by " +
                 "Challenge Show/Build Gameplay Unit Prefabs.")]
        public GameObject gameplayPrefab;
        [Tooltip("1 = base form, 2 = middle, 3 = final evolution.")]
        [Range(1, 3)] public int evolutionStage = 1;

        [Header("Measured Silhouette")]
        [Tooltip("Standing height in metres, measured from the source prefab.")]
        public float height = 1f;
        [Tooltip("Body width in metres, ignoring outstretched limbs.")]
        public float bodyWidth = 0.6f;

        [Header("Collider")]
        public float colliderRadius = 0.3f;
        public float colliderHeight = 1f;
        public float colliderCenterY = 0.5f;

        [Header("Physics")]
        [Tooltip("Rigidbody mass. Heavier units resist the arm; lighter units fly further.")]
        public float mass = 20f;
        [Tooltip("Extra drag applied while running, keeps light units from skating.")]
        public float linearDamping = 0.5f;

        [Header("Locomotion")]
        public Locomotion locomotion = Locomotion.Biped;
        [Tooltip("Target lane speed in metres/second.")]
        public float moveSpeed = 4f;
        [Tooltip("How quickly the unit reaches moveSpeed. Low = sluggish heavy feel.")]
        public float acceleration = 12f;

        [Header("Impact Response")]
        [Tooltip("Speed change (m/s) a hit must impart to knock this unit down. Expressed as a " +
                 "velocity rather than an impulse so it stays meaningful across a 20x mass range.")]
        public float stabilityVelocity = 4f;

        [Header("Durability")]
        [Tooltip("Total damage this unit absorbs before it stops getting back up. ~3 = three " +
                 "meaningful arm strikes.")]
        public float toughness = 3f;
        [Tooltip("Speed change (m/s) below which a strike is only a shove: no damage, no knockdown.")]
        public float hitDamageThreshold = 3f;
        [Tooltip("Speed change (m/s) that counts as one full strike, i.e. 1.0 damage. Severity " +
                 "scales from this, clamped so a clean hit never lands outside 0.75-1.25.")]
        public float fullHitDeltaV = 6f;
        [Tooltip("Scales the impulse the arm imparts. >1 = launches further than its mass implies.")]
        public float knockbackMultiplier = 1f;
        [Tooltip("Extra impulse spread across ragdoll bones on activation, for exaggerated flailing.")]
        public float ragdollImpulseMultiplier = 1f;

        [Header("Ragdoll Budget")]
        [Tooltip("Maximum ragdoll bodies to generate. Keeps solver cost predictable.")]
        [Range(3, 20)] public int ragdollBoneBudget = 9;
        [Tooltip("Bones shorter than this fraction of the rig's LONGEST bone are skipped (fingers, " +
                 "toes, jaws). Relative to the rig itself, not to the creature's overall height.")]
        [Range(0.05f, 0.6f)] public float ragdollMinBoneLengthRatio = 0.25f;
        [Tooltip("Bone names containing any of these are never given a ragdoll body.")]
        public string[] ragdollExcludeNameContains =
        {
            "Finger", "Thumb", "Toe", "Jaw", "Feeler", "Platform", "Dummy", "Index", "Pinky"
        };

        [Header("Recovery")]
        [Tooltip("Seconds the ragdoll must lie there before standing up, so the impact reads on camera.")]
        public float recoveryMinimumRagdollTime = 0.45f;
        [Tooltip("Seconds of arm immunity while standing up and re-orienting.")]
        public float recoveryImmunity = 0.95f;
        [Tooltip("Height above the landing surface the root is placed at. Non-zero for units that " +
                 "hover rather than stand - Skeleton Mage flies, so it must not be planted on the deck.")]
        public float recoverGroundOffset;

        [Header("Animation")]
        [Tooltip("Animator state played while running. Names differ per monster — Skeleton only has " +
                 "'Creep Dash Forward In Place', Skeleton Mage only 'Fly Forward In Place'.")]
        public string runStateName = "Run Forward In Place";
        [Tooltip("Animator state played on the family island and before the run starts.")]
        public string idleStateName = "Idle";
        [Tooltip("Animator state played while standing back up. Resolved per rig: Resurrect where " +
                 "it exists (the two Skeletons), otherwise Take Damage, which all 15 have.")]
        public string recoverStateName = "Recover";

        [Header("Lifecycle")]
        [Tooltip("Seconds a ragdoll may tumble before we stop waiting for it to settle and force the " +
                 "recovery (or defeat) decision.")]
        public float ragdollTimeout = 5f;

        /// <summary>Rough archetype label, derived from measurements. Display/logging only.</summary>
        public string SizeClass =>
            height < 1.4f ? "Light" :
            height < 2.4f ? "Medium" : "Heavy";
    }
}
